File transfer using secure copy

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,26 +1,26 @@
 #!/usr/bin/env bash
-# Check if there are enough arguments
-
+# checking for command line arguments
 if [ $# -lt 4 ]
 then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-	exit 1
-# Assigning parameters for variables
+  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+  exit 1
+fi
+
+# assigning parameters to variables
 
 path_to_file=$1
 ip=$2
 username=$3
 path_to_ssh_key=$4
 
-# Disabling Srict host key
 
-scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+# disabbling strict host key checking
+scp -o "StrictHostKeyChecking no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
 
-# Checking if file transfer was successfull
-
+# checking if the transfer was successful
 if [ $? -eq 0 ]
 then
-	echo "FILE TRANSFER WAS SUCCESSFULLY CARRIED OUT"
+  echo "FILE TRANSFER WAS SUCCESSFULL"
 else
-	echo "FILE TRANSFER FAILED"
+  echo "FILE TRANSFER FAILED"
 fi
