File transfer

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,12 +1,26 @@
 #!/usr/bin/env bash
 # Check if there are enough arguments
 
-if [ "$#" -lt 3 ]
+if [ "$#" -lt 4 ]
 then
-    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
-elif [ "$#" -eq 3 ]
+	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+# Assigning parameters for variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# Disabling Srict host ket
+
+scp -o "StrictHostKeyChecking=no" "path_to_ssh_key" "path_to_file" "username@ip:~/"
+
+# Checking if file transfer was successfull
+
+if [$? -eq 0]
 then
-    scp -o StrictHostKeyChecking=no "$1" "$3@$2:~/"
+	echo "FILE TRANSFER WAS SUCCESSFULLY CARRIED OUT"
 else
-    scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~/"
+	echo "FILE TRANSFER FAILED"
 fi
